name: CI

on: [push]

jobs:
  rubocop:
    name: Run RuboCop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3  # プロジェクトのRubyバージョンに合わせて変更
          bundler-cache: true

      - name: Create .env file
        run: echo "REACT_APP_GOOGLE_MAP_API_KEY=${{ secrets.REACT_APP_GOOGLE_MAP_API_KEY }}" > frontend/.env

      - name: Set up Docker
        run: docker compose up -d

      - name: Run RuboCop inside Docker
        run: docker compose exec -T api bundle exec rubocop
